# Generated by Django 2.0.9 on 2021-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='seb_keyhash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
