version: "3.9"

services:
  ubuntu:
    build:
      context: ./ubuntu
    command: /bin/sh -c "while sleep 1000; do :; done"
  jupyter:
    build:
      context: ./jupyter
    ports:
      - 5001:8888