# Generated by Django 2.0.9 on 2021-07-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_directtolabaccount_submission_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
